name: flutter_field_validator
description: A simple field validator for Flutter.
version: 2.0.0
repository: https://github.com/kirchesch/flutter_field_validator

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
